name: Upload to PyPI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine bump2version

      - name: Increment package version
        run: |
          python3 -m bumpversion --current-version $(cat VERSION) patch VERSION

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Commit & Push changes

        # if u gonna reuse this step in ur workflow file
        #   first allow `read and write` pessmissions in
        #     repo settings actions>general>workflow permissions section

        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: "axdjuraev@gmail.com"
          author_name: "axdjuraev"
          branch: "main"
          message: "bump-version"
          directory: .

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --repository pypi dist/*
